name: Check lint

on:
  push:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - '.github/workflows/*.yml'
      - 'packages/*/package.json'
      - 'package.json'
      - 'package-lock.json'
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
      - run: npm run clean && npm run compile
      - run: npm run lint
