# This is a basic workflow that is manually triggered

name: Test:shared

on:
  push:
    paths-ignore:
      - "examples/**"
      - "README.md"
      - ".github/workflows/*.yml"
      - "packages/*/package.json"
      - "package.json"
      - "package-lock.json"
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache solana-localhost-devnet-keypair 
      id: cache-keypair
      uses: actions/cache@v3
      with:
        path: /tmp/solana-localhost-devnet-keypair
        key: ${{ runner.os }}-cache
    - run: npm ci
    - run: npm run test:shared
